sudo: required
services:
- docker
language: c
env:
  global:
  - secure: AKQSgH7oJXDtHBPTcoW2wNpQlCXbC3SkyeLR2SHVlFokM7WkDsEOtBd6VVonRgEafUGuBgM33Ym3Q8PmPavdxKxnAItba57f6GaAZzPfULFpkJNLSl/lr2oaLZzczGy299PDsl3WdJUZ547ZHFb2SUvLQzJh7VM1kqUBY883dCf1Eg7iuMOMZKiX3ZJv+EX290EOBiD078i9XSKjBpMGi3doyIwsw1mQabB7zLe5gYJpy+Iw50mHSEZnCqEaizDvzaMwqUmGyn4w8eU1ZabtlyJuYh6dHm4CNj/Bnhl9+YX0hWNGKKu8jojJx4SUzcaWzUrYqXvBgTm3c1XfQT525w+3WR77v8RNb8L2RsfKZ7JKgL4ehUe8kWRjbvk13YmrprUOjHmlUsMDL3+4uV6nD82pNiZwsW5L/ISLJCgU094EMWzJoH0S9MYB7a6rdYertxVKpAs/37K8SJCBTiGDMxx8oId27dZ1D9a2ZtsvRnvOP/j1zouaz697vPWAhHKpWIQXKqwLYwLukahD2lGknrlJUoafpGK1nqZGiYq/ZycWI8NhcmobEcUP+OBJJZc3Sgb+m31acQiaepbQQlxBP9r++LJhbhkqXRv0wFH/jQD67JpLZUvZ4/9nEy9huKzVTH4ejoy3VXg/cC9vAYP6hIduDrrq7WIiFGd0V9C+gmk=
  - secure: TI0SNmYVKTXg2dkT645SHqsrEgjmFUM4Ojps2uNm4DEZw5LBBBFzLcT7Xn+eWoG+rRxGnWwt7ZINlS/4c3XRjT1yxBBaMF7Hv/IflmJDSl0J8fYbtub613h9cc9hLkwGVT2M3cq6M0iWsmssIy9NuEk9jDQm2NOfplPNNJz6CFWVM1ImJSyCRJSn1V1mSeRJ9KISFqIj90u4ihI0NKDkV75JfDW4aPv5rjkaSKc/pE32fzp3FAqsVEepQfRcmrieq3XMT11ixQ4uBTi017TbD7cFaNunzj6Sf0q0Ab8mpb2zcTzC3l8xPED2i/QMqf6BSJ16E/kS8q2+r2+ttszihAqrayOzpAOv0TznOc3efg8Lnd/zJSQdP3ayeCdLG+u7ieVSsHAsGCasRlWmnTtGGj1fmR22eYLu80D9MNP5Bhpyhkxf3xSQASLYFYRxPpk3R9/igp3IaQxuAQDU+WtQWqGhsN3Xau4OhE9CsNhS4gNvwlkJx04+BRDG2gKlE9pNtTiCL1aslv+cYAXVhw+qMlKihxNrcWPvRX+uSFaNfS4xnH3ysSszmjB7zc4cL8Q3e32ejh6OtxPoEsFYDRSDF9X5mFSCFoM9/dbzc/W3eJRFFoYIEUVMdzKwyBKRjLK2O1+7su6OT4RWJdcgbISXsth4RwcYVwznq2f9aTtOVhY=
  - secure: a7X+KbNg6LxO97CT5FAxaK4hyeY2ah0VXwvPADVUFgkBPOLxZt3x29IamOIWYd4VeVoVTuWKNPMztCmyHm/gbjXxDWffqeq823lKE7Bkc0VL7ca2k1Q6CrUOjnIeTA+OVLiXWUEPTVGO4u3ldfel0yPeUysrNTpjNdRloQSLjudpYw8ECSk+a6yMm5QCK8DrHfFNFK+BuQCbaiT5ORBnLHIQ65bEdmXoD9qhKAd4l/lO5U4DNrUA3p+1O+N7YcukMtV3tQy6SVkspm0gHnrV8k92bvvdAez5diV+IQrL8BxUDQbmm0NbMcLbM5C+9Rv9ANWYY7U4HBIJS8t5V4vT97WJTgYFuXGUIagY/4uOz0nrKIcSKVfOqRfseu1V0F0NdE7bMXycchALju6MUILdUjGHJVCOjGGOlYkDXIOHft46MvtE3E6AWE/X8nqIohTMq4Zc4jw6a1lVxXkDp66fJEqWCwHZfpHYJSC837pmMAuxPrK43gJBZLiF5I7gTdmGdyG7GjpJyH8uqL/a82SkGkID8FRdRHlOgpn1mc9+h9eIKNPs7opwMHJi4Y/vXIEMmrVujPUkSKMDsMAnVyJWdCizVqGDc8PHUr39NOyVuZ5RFzovTy6QgzwN2oca5QFqc+i/rNo9acYwwBkRZfRBU1tR7IxOEz7RNxcfWbBj6qc=
  - COMMIT=${TRAVIS_COMMIT::8}
script:
- echo "Building BE-AD docker image..."
after_success:
- git submodule init
- get submodule update
- docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASS
- export REPO=andorp/bead
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
