sudo: required
services:
- docker
language: c
env:
  global:
  - secure: i8+iTiNMVfd+TejRWjoSlCHUUuYP31IAqP8C4qwNNGAl0hBin9ogHCu3NnHTluDynJMaavxOAYGN4PIGrZJX3zirJRRrzozPyo2d4rHjz1twy97MchHVEUZUKAcZmIO87RwJtJxEo5Kb6FaFx4pV3taoVnW0qi50/h/fab0xgmPAt52x0scqn73udAznnBs6qHwi0we/aVzLwWp9wRMtLn3Od4eD21uGxLMFCbgI6FYKsbs9Njp2cKeRFLu7ADuuY4JdhpMNLi5FNwFTZkUfvyCTFgjc+o8GaBbTWMkvdjQ2kRH1n0Px1RGUGhbi3FqN0v03/IeEfv0GiB5UaEXK7tUrBo2Ya45ifSliaXMg9zzgFqQw7Bu3xFykgtzYmiO70LRRf+1vUjj5aDGB213GAm0DyWRmutBosfrMx/2OtvLet63PRy8+PNuQGLaxFvYmBmDujyRXpY6bTr+O9ZxaVqIkr9uycjldkvvhU60Y3BrqrPzwBtLyN/BP571czEIqAjX91q3jK/g6YczHM8JXwFKkH/49hG70CBmrif3ec3EVq991qJAgvBGa8N5KBFpH3j4ODPS813Wxg613fUWiHSrXO4SuczJS4NdlwoeVyCLJ+FaSdBywHuHVdU6u25SVFJZ8zssJ7Lk5KQDihIlGuPE6MbaRfWzQYNh1yAIiJQo=
  - secure: Ipj4IZwg7nqRclXMatUUmVZVOiVNlBhDql6nZNAAtVOY0aVEHRE4tEVSVpgsQQftRWSVyMXRDXaH3ZinKFUCEgrOeZESkxrawdEmjhpUXClboXL06XM1orBaelJ7eVZ+N1wSSHrSopSIxAPR6neD+9kcvTzG+FSJCZPrZP2C9/JHK+8NcBvz3hk/GjVnj4kxW+iBnE4Koc2z+B5r80ub9p5O1+5we9L3R4rFZPpukLJLSmhUf+K3xxXCIQJKv4Yv/D0p83RGvyAveoRxyKXdZiG7yZxGwonaUPO9Gz/+rE/Zcg3KLP/X1KIihz4x1D1iYlg7pVhpf2WMGwreL4bS4F6V5zdzoXnRA/9jpKbiFeZKfRH/pVgOwKiZYdgVZ+ONI0+qEQAaIdZHAYa4W+FhMeDsaoIcUwJ4wo4vf3DK4jhbmbCXEyxepIKSUB9ivdhuLmCwVkYFuXMRAOW7xFlQYkeDeahyd3paeyYBGt9ZKPaOeJqVf1//Ia0beQG+KOLg4EmHZeGTfGOEg9fpE9Y+3cIGA1GcScFwnSI75ESCu5DeQh9qx6GG65O0ZXvQQExP4MmAWSz9J3NUd3yUHsimWlTZU17krkbtpsDSj70GN/My7RJmdfbNgzVqcipEULz3aEdom9KiOgyCI2x1gNJgtFyPLF1Val6JT6Hgb/74IAc=
  - secure: X0h3Y8KchmLuqntvHglajKvTimXvf3G/q3wFgUbJQoh9RFBTVGzo5Iq3Nt4S0SeNaGDOkivTBWoWEGSlW+6sFpPNu17I+KeM8rrsKUAfh5z4Q6WSeHJRHNkS2keXiAr93kHNCNOm/BVshplh0ylIRuumb940E6eEvhNNGL6xz7xMQxKWoDBRRBGG5MclZLtoEw4LGbuRXR8uXWm8h02o+8vbD5bFG3OR+sCamNzHlL5R7SXw2qrm+fFR1WIfL/ZcSdzJsu72l1v2SBvoCGFVkMl4eNnzODGyZev1ntzdyB936LVI20MZSklNTT4jUe9nrpCaPX6lxU2a9Ig9KI6OSLnO4Q+0Rb7sFoBRqLl9CQkVUdBpBTDHLEL0Ap/zf4Znor8YHJJqvZuh69zUo/Xhe7vUBjhS9pkY89DChtaXs0fdRjxq8bGrDrwht3GogXHGd6KBNv44/GBXsJNeqiSCF5dLxXMGhoCPzwqCKPvA/2KoRwCml76r804Sca5ODBJH8P6KsFeOGBy8MB0EFjj4+ziMLHDqAIlnSYvswmHztyYVZ3g2MshqtEh/Ny7ImFt9FzeabZ687LpfaBdy8e3i0hoDbVbsg+RfeGLINLB7REOgZGaZEDK4plDPfnSXT5cTSGic+dJTllKXVGwpoqxR+18v4kZJWqyJDjZRfp4NLW8=
  - COMMIT=${TRAVIS_COMMIT::8}
script:
- echo "Building BE-AD docker image..."
after_success:
- git submodule init
- get submodule update
- docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASS
- export REPO=andorp/bead
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker $REPO:$TAG
- docker push $REPO
